# Simple Time Service (STS) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-deploy
  namespace: dev
  labels:
    app: sts

# Deployment specification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sts
  template:
    metadata:
      labels:
        app: sts

# Pod specification
    spec:
      containers:
        - name: sts-container
          image: ahsan98/sts:1.0                # Replace with your image name and tag from Docker Hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          # Resource Management
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          # Liveness Probe – container alive?
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          
          # Readiness Probe – ready for traffic?
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
# Service to expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: sts-svc
  namespace: dev
  labels:
    app: sts

# Service specification
spec:
  type: NodePort
  selector:
    app: sts
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
