# Service to expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: sts-svc
  labels:
    app: sts

# Service specification
spec:
  type: LoadBalancer
  selector:
    app: sts

# Service ports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080